name: WorldFinder
main: nl.thedutchmc.worldfinder.WorldFinder
version: @version@
author: TheDutchMC
api-version: @apiVersion@
commands:
  findworld:
    description: TODO
  worldfindertp:
    description: TODO

